### ISSUE TITLE
Rip Me

### ISSUE THREAD

**Issue by ghost** [aurelius88/utility-box#1]
Hi can you please help me how to write the command right. If I want to hook S_USER_STATUS. 3 I need the group, packet name, version and at least one var if I try utils hook add S S_USER_STATUS 3 XX the XX should be the var its not working.

**Comment by ghost** [comment]
Same goes for location it only throws errors if I use the command.

**Comment by aurelius88** [comment]
About **adding hook**:
If you got a message like 

> group:S, name: S_USER_STATUS, version: 3, vars: ["XX",...]

then you successfully added the hook. To really start hooking now, you need to use `util scan S` S is the group name. But... the predefined group S is a large one containing all hooks from server that got packet definitions so far. This group is still not working, because one or more hooks inside are not working. So to be safe, just assign your hook to another group, a new one like:
`util add hook user-status S_USER_STATUS 3 status bySkill` and start it with
`util scan user-status`
Be aware that variables are case sensitive. These variables should be exactly as defined in the packet definition. Otherwise it will print you "undefined" as value when the packet is received. 
As you might see, I did not add `gameId` as a variable. This is because of gameId is a BigInt and JSON.stringify - which I use for easy output - is not able to handle a BigInt, resulting in an error. It will be fixed in future versions. 

For **pos** the error has been thrown because there is no location that has been tracked so far. You can do the work around for now:

- `util scan movement`
- Move a bit
- Now you can use `util pos` and `util pos help` for more help

This will be improved in future.
If you want to print every position on each movement then use `util scan verbose`. Same goes for deacivating it again.

Thanks for your feedback.

**Comment by ghost** [comment]
Ok nice thanks for the answer.
